name: GHCR cleanup

on:
  delete:
  pull_request:
    types: [closed]
  workflow_dispatch:      # allows manual trigger from the GitHub UI 

permissions:
  packages: write

jobs:
  ghcr-cleanup:
    if: |
      (github.event_name == 'delete') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Determine deleted or merged branch
        id: sanitize
        run: |
          if [[ "${{ github.event_name }}" == "delete" ]]; then
            BRANCH_NAME="${{ github.event.ref#refs/heads/ }}"
            echo "Branch deleted: $BRANCH_NAME"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
            echo "Branch merged from PR: $BRANCH_NAME"
          else
            echo "Unknown event"
            exit 1
          fi

          if [[ "$BRANCH_NAME" == "main" ]]; then
            TAG="latest"
          else
            TAG="${BRANCH_NAME//\//-}"
          fi

          echo "Sanitized tag: $TAG"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Delete GHCR tag
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-tags: ${{ steps.sanitize.outputs.tag }}