---
name: maintenance branch removal

on:
  delete:

permissions:
  packages: write

jobs:
  ghcr-cleanup-branch-removal:
    name: GHCR cleanup branch removal
    runs-on: ubuntu-latest
    steps:
      - name: sanitize tag
        id: sanitize
        run: |
          BRANCH_NAME="${{ github.event.ref }}"  # Get deleted branch name
          if [[ "$BRANCH_NAME" == "main" ]]; then
            TAG="latest"
          else
            SANITIZED_BRANCH="${BRANCH_NAME//\//-}"
            TAG="$SANITIZED_BRANCH"
          fi
          echo "TAG=$TAG"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-tags: ${{ steps.sanitize.outputs.tag }}