---
name: maintenance

on:
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:      # allows manual trigger from the GitHub UI

permissions:
  packages: write

jobs:
  cleanup-ghcr:
    name: Cleanup GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-ghost-images: true
          delete-orphaned-images: true
          delete-partial-images: true
          dry-run: true

